server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.166.20:3306/bw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bowen123
  resources:
    static-locations: classpath:/templates  #访问静态页面